apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-matrix-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'unbound-matrix-telemetry'
        static_configs:
          - targets: ['unbound-matrix-service:8080']
